name = "id1"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "103.133.223.52:2096"
UUID = "2d31d87f-78bf-4410-97c9-a8a083211eb7"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
