name = "test1"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "a4a48e8f-e3d0-4797-bbeb-5587fba988d9"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
