name = "sg2"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[[routes]]
pattern = "sg2.taoovpn.cloud"
custom_domain = true

[vars]
PROXYIP = "143.198.213.197:443"
UUID = "99e09016-356b-4f35-918f-f57567e3da0e"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
